version: "2"
services:
  companion-service:
    container_name: companion-service
    build: ./
    command: nodemon --experimental-modules | bunyan
    ports:
      - "3000:3000"
    tty: true
    volumes:
     - .:/usr/src/app
    env_file:
        - .env
